---
###
# install-dependencies playbook
##
# Used by ./tads install-dependencies
##

- hosts: localhost
  tasks:
    - name: Install Vagrant, Virtualbox and other dependencies (linux)
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - virtualbox
        - vagrant
        - jq
      when: ansible_facts['os_family'] != "Darwin"

    - name: Install Vagrant & Virtualbox (mac)
      become: no
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - virtualbox
        - vagrant
      when: ansible_facts['os_family'] == "Darwin"

    - name: Other dependencies (mac)
      become: no
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - coreutils # for GNU ls
        - jq
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Terraform (linux)
      shell: >
        wget -O /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        && unzip -d ~/.local/bin /tmp/terraform.zip
        && rm -f /tmp/terraform.zip
      environment:
        TERRAFORM_VERSION: 0.12.12
      args:
        creates: ~/.local/bin/terraform
        warn: False
      when: ansible_facts['os_family'] != "Darwin"

    - name: Install Terraform Homebrew Tap (Mac)
      homebrew_tap:
        name: hashicorp/tap
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Terraform (Mac)
      homebrew:
        name: hashicorp/tap/terraform
        state: present
      when: ansible_facts['os_family'] == "Darwin"

- hosts: localhost
  tags:
    - dev_dependencies
  tasks:
    - name: Install ansible-lint and molecule
      become: True
      pip:
        name:
          - ansible-lint
          - docker
          - molecule==2.22
          - molecule[docker]

    - name: Install shellcheck
      become: True
      shell: >
        (wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv --directory /tmp)
        && cp "/tmp/shellcheck-${SHELLCHECK_VERSION}/shellcheck" /usr/bin/
        && rm -rf /tmp/shellcheck-${SHELLCHECK_VERSION}
      environment:
        SHELLCHECK_VERSION: v0.6.0
      args:
        creates: /usr/bin/shellcheck
        warn: False
